### ISSUE TITLE
Kan ikke forbinde til api.statbank.dk 

### ISSUE THREAD

**Issue by kf-randers** [Randers-Kommune-Digitalisering/vis-klimadata-initiativer-aktiviteter#189]
Node-RED producerer nedenstående fejl i loggen, når den førsøger at hente data fra Danmarks Statistik. Det hele virker fint, når man kører det op lokalt. Kan der være tale om en netværksfejl (getaddrinfo EAI_AGAIN)?

```
{
  DST: 'error encountered',
  Error: {
    message: 'RequestError: getaddrinfo EAI_AGAIN api.statbank.dk',
    source: {
      id: '2980a9d28e4700dd',
      type: 'http request',
      name: undefined,
      count: 1
    },
    stack: 'RequestError: getaddrinfo EAI_AGAIN api.statbank.dk\n' +
      '    at ClientRequest.<anonymous> (/usr/src/node-red/node_modules/got/dist/source/core/index.js:970:111)\n' +
      '    at Object.onceWrapper (node:events:628:26)\n' +
      '    at ClientRequest.emit (node:events:525:35)\n' +
      '    at ClientRequest.origin.emit (/usr/src/node-red/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)\n' +
      '    at TLSSocket.socketErrorListener (node:_http_client:494:9)\n' +
      '    at TLSSocket.emit (node:events:513:28)\n' +
      '    at emitErrorNT (node:internal/streams/destroy:157:8)\n' +
      '    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:83:21)\n' +
      '    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)'
  }
}
```

**Comment by rak-randers** [comment]
All porte er åbne:
https://github.com/Randers-Kommune-Digitalisering/kithosting-randers-kommune-apps/blob/test/vis-klimadata-initiativer-aktiviteter/templates/netpol.yaml#L21-L27

**Comment by rak-randers** [comment]
Problemer med DNS på platformen - har kontaktet KIT
